export const ADD = "ADD";
export const UPDATE = "UPDATE";
export const DELETE = "DELETE";
export const GET_CART = "GET_CART";

export const APPLY_FILTER = "APPLY_FILTER";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";

export const GET_FILTERS = "GET_FILTERS";
export const GET_FILTER_BY_ID = "GET_FILTER_BY_ID";
export const SELECT_FILTER = "SELECT_FILTER";
export const SET_FILTERS = "SET_FILTERS";
export const FILTERS_SELECTED = "FILTERS_SELECTED";

export const GET_BILLING_INFO = "GET_BILLING_INFO";
export const UPDATE_BILLING_ADDRESS = "UPDATE_BILLING_ADDRESS";
export const UPDATE_SHIPPING_ADDRESS = "UPDATE_SHIPPING_ADDRESS";
